version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile  # Specify the Dockerfile name if it's different
    ports:
      - "3001:3001"
    depends_on:
      - client

  client:
    build:
      context: ./client
      dockerfile: Dockerfile  # Specify the Dockerfile name if it's different
    ports:
      - "3000:3000"
